plugins:
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Bundler/GemFilename:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: describe

Naming/HeredocDelimiterCase:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
